export const THEMES = ["Monad", "Multisynq", "Tech", "Web3"] as const;

export const AI_CONTEXTS = {
  monad:
    "Monad is a next-generation Layer 1 blockchain fully compatible with the Ethereum Virtual Machine (EVM), designed to address the scalability and efficiency issues that have hampered widespread blockchain adoption. Monad offers high throughput of up to 10,000 transactions per second (TPS), low transaction fees, and a familiar developer experience for Ethereum users. Its ultimate vision is to create a platform with no compromises between speed, scalability, security, and decentralization, while upholding openness and permissionless participation. Monad's key features include: (1) Optimized Consensus: 1-second finality and 0.5-second block time, ensuring transactions are instant and the network remains decentralized. (2) Parallel Execution: transactions are processed in parallel using multi-core CPUs, enabling up to 10,000 TPS. (3) MonadDB: SSD-based state storage, lowering node costs and encouraging validator participation. (4) Asynchronous Execution: the separation of the consensus and execution layers keeps the system responsive. (5) Full EVM Compatibility: all Ethereum smart contracts can be executed without modification. Monad is suitable for a wide range of applications such as DeFi, NFT, gaming, enterprise applications, and social platforms. Monad maintains security and decentralization without sacrificing performance. Compared to Ethereum, Monad offers higher TPS, faster finality, and better storage efficiency. The Monad team consists of Keone Hon (CEO), James Hunsaker (CTO), and Eunice Giarta (COO), with strong backgrounds in distributed systems and high-frequency trading. Monad has raised $225 million in funding from leading investors including Paradigm, Electric Capital, and Coinbase Ventures. For more information, visit https://www.monad.xyz/",
  multisynq:
    "Multisynq is an open-source JavaScript library that enables developers to build real-time multiplayer applications without traditional server-side code. Multisynq uses a deterministic, peer-to-peer approach where each client runs the same logic in a synchronized virtual machine environment, ensuring that the application state is always identical across all participants. Its architecture separates the Model (pure, deterministic logic) from the View (UI and user interactions). Interactions are driven by an event system—every user action triggers an event that is propagated to all clients, then processed identically on each device. Multisynq uses a synchronization network (Synchronizer) to distribute events between clients without running application code, making it crash-resistant, low-latency, and extremely lightweight. Key advantages include: serverless multiplayer, deterministic state, very low latency, flexible for a wide range of application types (games, collaborative tools, dashboards), and open protocols. However, because all the logic resides on the client, Multisynq is better suited for applications with low security risks such as casual games, whiteboards, or educational simulations. Example use cases include: collaborative editors, real-time whiteboards, games synchronous, and interactive educational tools. Multisynq has raised $2.55 million in funding, including $2.2 million in a seed round in April 2024 and $350K from a public sale in February 2025. To get started with Multisynq, developers simply define models and views in JavaScript, then connect to a public or self-hosted Synchronizer node. Official documentation and APIs are available at https://multisynq.io/docs.",
  web3: `
Web3 is a decentralized internet powered by blockchain technology, where users control their data, identity, and interactions. A sentence about "web3" should refer to decentralization, smart contracts, crypto wallets, or DAOs. Keep it simple and relevant to typing practice.
`,
  tech: `
Tech refers to the broad category of modern technologies, including software engineering, artificial intelligence, cloud computing, cybersecurity, and emerging innovations that shape how we live and work. A sentence about "tech" should reflect tools, platforms, programming, or future-facing ideas. Example keywords include: code, data, apps, innovation, robotics, or algorithms.
`,
} as const;
